#!/bin/bash
echo "This should install all packages that are needed by this program , if you dont have Ubuntu/Debian - apt-get you should install them manualy!"
sudo apt-get install g++ imagemagick mpg123 freeglut3 freeglut3-dev glutg3 glutg3-dev libxxf86vm-dev
exit 0
