#!/bin/bash
#-b 0
bin/Release/FlashySlideShow bin/Release/FlashySlideShow -mv_sort -sfx -r -fd -q 6 -t 1 -d 6000 "/home/ammar/Pictures/Pictures/'11_04_14_01"
#"/home/ammar/Pictures/Beauty/"
#"/home/ammar/Downloads/"
# "/home/ammar/Documents/Programming/FlashySlideShow/app_clipart"
#"/home/ammar/Pictures"
exit 0
