#!/bin/bash
  

echo "Compiling libAmmServerlib.a null version / Author : Ammar Qammaz"  
LIBNAME="libAmmServerlib.a"

if [ -e $LIBNAME ]
then
  rm $LIBNAME
fi   

# -O3 -fexpensive-optimizations
CFLAGS="-s"

gcc -c $CFLAGS main.c -o main.o 

PARTS_OF_LIB="main.o"

ar  rcs $LIBNAME $PARTS_OF_LIB

rm $PARTS_OF_LIB

if [ -e $LIBNAME ]
then
  echo "Success.."
else
  echo "Failure.."
fi



exit 0