Document: flashyslideshows
Title: Debian flashyslideshows Manual
Author: <insert document author here>
Abstract: This manual describes what flashyslideshows is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flashyslideshows/flashyslideshows.sgml.gz

Format: postscript
Files: /usr/share/doc/flashyslideshows/flashyslideshows.ps.gz

Format: text
Files: /usr/share/doc/flashyslideshows/flashyslideshows.text.gz

Format: HTML
Index: /usr/share/doc/flashyslideshows/html/index.html
Files: /usr/share/doc/flashyslideshows/html/*.html
