#!/bin/bash
#-b 0
bin/Release/flashyslideshows -file_resize 1024x768 -sfx -r -fd -q 2 -t 1 -d 6000 "/home/ammar/Downloads/" 
#"/home/ammar/Pictures/Pictures/'12_03_03_01(Tritsi)"
#"/home/ammar/Pictures/Pictures/'12_02_26_01(Kalavryta)"
#"/home/ammar/Pictures/Pictures/'11_04_14_01"
#"/home/ammar/Pictures/Beauty/"
#"/home/ammar/Downloads/"
# "/home/ammar/Documents/Programming/FlashySlideShow/app_clipart"
#"/home/ammar/Pictures"
exit 0
