#------------------------------------------------------------------------------#
# This makefile started its life generated by 'cbp2make' tool rev.138 , it is now
# kept by hand because the generated copy went stale ( it still listed the long
# gone visuals/effects.cpp and never learned about the shader code ) .
# The source list below has to stay in sync with the one in CMakeLists.txt , the
# cmake build in build/ and this makefile compile exactly the same files.
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

# JPG/PNG support is compiled in , same as the default of the cmake build
DEFS =  -DUSE_JPG_FILES -DENABLE_JPG -DUSE_PNG_FILES -DENABLE_PNG
INC =
CCFLAGS =  -Wall $(DEFS) -march=native -mtune=native
CFLAGS =  $(CCFLAGS) `wx-config --cflags`
RESINC =
LIBDIR =
LIB =  -lglut -lGL -lGLU -lGLEW -lXxf86vm -lpthread -lopenal -lalut -ljpeg -lpng -lrt -lm
LDFLAGS =  `wx-config --libs`

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
CCFLAGS_DEBUG =  $(CCFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG =
OUT_DEBUG = flashyslideshows

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -fexpensive-optimizations -O3
CCFLAGS_RELEASE =  $(CCFLAGS) -fexpensive-optimizations -O3
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE =
OUT_RELEASE = flashyslideshows

# The application itself
SRC_CXX = main.cpp \
          controls.cpp \
          camera_control.cpp \
          pictures_control.cpp \
          scene_objects.cpp \
          slideshow.cpp \
          visuals.cpp \
          visuals/background.cpp \
          visuals/dynamic_background.cpp \
          visuals/shadertoy.cpp \
          visuals/hud.cpp \
          visuals/picture_renderer.cpp \
          transitions/transition_handler.cpp \
          transitions/shader_transitions.cpp \
          tools/commandlineParser.cpp \
          tools/environment.cpp \
          tools/image_sensing.cpp \
          tools/joystick.cpp \
          tools/jpegexiforient_embed.cpp \
          tools/math_3d.cpp \
          tools/scriptIntegration.cpp \
          tools/sound.cpp \
          tools/vsync.cpp \
          tools/webinterface.cpp \
          tools/wxwidgets_stuff.cpp \
          layouts/expo_layout.cpp \
          layouts/layout_handler.cpp \
          hypervisor/load_images.cpp \
          hypervisor/load_textures.cpp \
          hypervisor/memory_hypervisor.cpp \
          filesystem/directory_listing.cpp \
          filesystem/directory_sorting.cpp \
          filesystem/directory_transactions.cpp

# The image codecs , cmake builds these as the separate Codecs static library
SRC_C = Codecs/codecs.c \
        Codecs/pfmInput.c \
        Codecs/ppmInput.c \
        Codecs/bmpInput.c \
        Codecs/asciiInput.c \
        Codecs/pngInput.c \
        Codecs/jpgInput.c \
        Codecs/jpgExifexternal.c \
        Codecs/jpgExiforient_embed.c

OBJ_DEBUG = $(addprefix $(OBJDIR_DEBUG)/,$(SRC_CXX:.cpp=.o) $(SRC_C:.c=.o))

OBJ_RELEASE = $(addprefix $(OBJDIR_RELEASE)/,$(SRC_CXX:.cpp=.o) $(SRC_C:.c=.o))

all: debug release

clean: clean_debug clean_release

before_debug:

after_debug:

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $< -o $@

$(OBJDIR_DEBUG)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CCFLAGS_DEBUG) $(INC_DEBUG) -c $< -o $@

clean_debug:
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)

before_release:

after_release:

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c $< -o $@

$(OBJDIR_RELEASE)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CCFLAGS_RELEASE) $(INC_RELEASE) -c $< -o $@

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release
